/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as HoodiesRouteImport } from './routes/hoodies'
import { Route as MugsRouteImport } from './routes/mugs'
import { Route as TshirtsRouteImport } from './routes/tshirts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const HoodiesRoute = HoodiesRouteImport.update({
  id: '/hoodies',
  path: '/hoodies',
  getParentRoute: () => rootRouteImport,
} as any)
const MugsRoute = MugsRouteImport.update({
  id: '/mugs',
  path: '/mugs',
  getParentRoute: () => rootRouteImport,
} as any)
const TshirtsRoute = TshirtsRouteImport.update({
  id: '/tshirts',
  path: '/tshirts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/hoodies': typeof HoodiesRoute
  '/mugs': typeof MugsRoute
  '/tshirts': typeof TshirtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/hoodies': typeof HoodiesRoute
  '/mugs': typeof MugsRoute
  '/tshirts': typeof TshirtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/hoodies': typeof HoodiesRoute
  '/mugs': typeof MugsRoute
  '/tshirts': typeof TshirtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/admin' | '/auth' | '/cart' | '/hoodies' | '/mugs' | '/tshirts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/auth' | '/cart' | '/hoodies' | '/mugs' | '/tshirts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/hoodies'
    | '/mugs'
    | '/tshirts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  HoodiesRoute: typeof HoodiesRoute
  MugsRoute: typeof MugsRoute
  TshirtsRoute: typeof TshirtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoodies': {
      id: '/hoodies'
      path: '/hoodies'
      fullPath: '/hoodies'
      preLoaderRoute: typeof HoodiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mugs': {
      id: '/mugs'
      path: '/mugs'
      fullPath: '/mugs'
      preLoaderRoute: typeof MugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tshirts': {
      id: '/tshirts'
      path: '/tshirts'
      fullPath: '/tshirts'
      preLoaderRoute: typeof TshirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  HoodiesRoute: HoodiesRoute,
  MugsRoute: MugsRoute,
  TshirtsRoute: TshirtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
